(defun c:startMyLsp()

	(load "D:/KSKLN/gitrepos/AutoLISP/drawThroughPoints.lsp")
	(load "D:/KSKLN/gitrepos/AutoLISP/ductAll.lsp")
	(load "D:/KSKLN/gitrepos/AutoLISP/ductOpening.lsp")
	(load "D:/KSKLN/gitrepos/AutoLISP/ductRoute.lsp")
	(load "D:/KSKLN/gitrepos/AutoLISP/getRoute.lsp")
	(load "D:/KSKLN/gitrepos/AutoLISP/myCommands.lsp")
	(load "D:/KSKLN/gitrepos/AutoLISP/myWallSketcher.lsp")
	(load "D:/KSKLN/gitrepos/AutoLISP/myRouteSketcher.lsp")
	(load "D:/KSKLN/gitrepos/AutoLISP/setLayers.lsp")
	(load "D:/KSKLN/gitrepos/AutoLISP/changeLayerFunctions.lsp")
	(load "D:/KSKLN/gitrepos/AutoLISP/myRectangle.lsp")
	(load "D:/KSKLN/gitrepos/AutoLISP/myRectangleOnEllipse.lsp")
	(load "D:/KSKLN/gitrepos/AutoLISP/updateExistingLayers.lsp")
	(load "D:/KSKLN/gitrepos/AutoLISP/blockOperations.lsp")
	(load "D:/KSKLN/gitrepos/AutoLISP/test.lsp")
)